ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine


COPY server /usr/src/server
COPY client/dist /usr/src/client/dist
RUN ls -lR /usr/src
WORKDIR /usr/src/server

RUN npm install
RUN npm run build

RUN find . -path ./node_modules -prune -o -print

# Run the application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE 3000

# Run the application.
CMD node dist/main