ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine

WORKDIR /usr/src/app
COPY server /usr/src/app
COPY shared /usr/src/shared
RUN ls -lR /usr/src

RUN npm install
RUN npm run build

RUN find . -path ./node_modules -prune -o -print

RUN mv ./public ./dist/server/public/

# Run the application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE 3000

# Run the application.
CMD node dist/main