import { PocketBase, RecordService } from "pocketbase"

export interface DbBoxer {
    id: string // Autogenerated 15-character alphanumeric string
    lastName: string // Required text field, max 255 chars
    firstName: string // Required text field, max 255 chars
    birthDate: string // Required date field (ISO format recommended)
    nbFights?: number // Optional integer field
    club: string // Required text field, max 255 chars
    weight?: number // Optional number field
    gender?: "male" | "female" // Optional select field
    license: string // Required text field
    userId?: string // Required relation to the user collection
    created?: string // Auto-generated timestamp
    updated?: string // Auto-updated timestamp
}

interface TypedPocketBase extends PocketBase {
    collection(idOrName: "boxer"): RecordService<DbBoxer>
}
